#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

fail() { echo "ANDROID_BUILD_PREFLIGHT_FAIL: $*" >&2; exit 1; }

command -v java >/dev/null 2>&1 || fail 'java is not installed.'
command -v javac >/dev/null 2>&1 || fail 'javac is not installed; a full JDK is required.'

JAVA_MAJOR="$(java -version 2>&1 | sed -n 's/.*version "\([0-9]*\)\..*/\1/p' | head -1)"
[ "$JAVA_MAJOR" = "17" ] || fail "Java 17 is required; found ${JAVA_MAJOR:-unknown}."

[ -n "${JAVA_HOME:-}" ] || fail 'JAVA_HOME must be set to the active JDK.'
[ -x "$JAVA_HOME/bin/java" ] || fail "JAVA_HOME does not contain bin/java: $JAVA_HOME"
[ -x "$JAVA_HOME/bin/javac" ] || fail "JAVA_HOME does not contain bin/javac: $JAVA_HOME"
JAVA_HOME_MAJOR="$("$JAVA_HOME/bin/java" -version 2>&1 | sed -n 's/.*version "\([0-9]*\)\..*/\1/p' | head -1)"
JAVAC_MAJOR="$("$JAVA_HOME/bin/javac" -version 2>&1 | sed -n 's/.* \([0-9]*\)\..*/\1/p' | head -1)"
[ "$JAVA_HOME_MAJOR" = "17" ] || fail "JAVA_HOME points to non-Java-17 JDK: ${JAVA_HOME_MAJOR:-unknown}"
[ "$JAVAC_MAJOR" = "17" ] || fail "JAVA_HOME javac is not version 17: ${JAVAC_MAJOR:-unknown}"

command -v flutter >/dev/null 2>&1 || fail 'Flutter SDK is not installed.'
FLUTTER_VERSION="$(flutter --version 2>/dev/null | sed -n '1s/Flutter \([^ ]*\).*/\1/p')"
[ "$FLUTTER_VERSION" = "3.47.2" ] || fail "Flutter 3.47.2 is required; found ${FLUTTER_VERSION:-unknown}."

SDK="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"
[ -n "$SDK" ] || fail 'ANDROID_SDK_ROOT/ANDROID_HOME is not set.'
[ -d "$SDK" ] || fail "Android SDK directory does not exist: $SDK"

for required in \
  "$SDK/platform-tools/adb" \
  "$SDK/build-tools/36.0.0/aapt2" \
  "$SDK/build-tools/36.0.0/apksigner" \
  "$SDK/platforms/android-36/android.jar" \
  "$SDK/ndk/28.2.13676358/source.properties"; do
  [ -e "$required" ] || fail "Required Android toolchain component is missing: $required"
done

[ -x android/gradlew ] || fail 'android/gradlew is missing or not executable.'

if [ -f android/local.properties ]; then
  # local.properties is generated by Flutter and must point at this host, not
  # contain a stale machine-specific path from a packaged source tree.
  if grep -Eq '^(flutter\.sdk|sdk\.dir)=(/home/user/|/Users/|[A-Za-z]:\\Users\\)' android/local.properties; then
    fail 'android/local.properties contains a stale machine-specific path.'
  fi
fi

# Exercise the patched wrapper before any expensive compilation. This catches
# malformed Gradle distribution extraction deterministically.
GRADLE_USER_HOME="${GRADLE_USER_HOME:-$ROOT/.gradle-preflight}"
export GRADLE_USER_HOME
./android/gradlew --version --no-daemon --console=plain >/tmp/hope-gradle-version.log 2>&1 || {
  cat /tmp/hope-gradle-version.log >&2
  fail 'Gradle wrapper could not start.'
}
grep -q 'Gradle 8.14.3' /tmp/hope-gradle-version.log || {
  cat /tmp/hope-gradle-version.log >&2
  fail 'Unexpected Gradle version; expected 8.14.3.'
}

printf 'ANDROID_BUILD_PREFLIGHT_PASS\njava=%s\njavac=%s\nflutter=%s\nandroid_sdk=%s\n' \
  "$(java -version 2>&1 | head -1)" \
  "$(javac -version 2>&1)" \
  "$FLUTTER_VERSION" \
  "$SDK"
